### ISSUE TITLE
Rails 4.2 compatibility

### ISSUE THREAD

**Issue by lukasztackowiak** [grosser/bitfields#14]
I'm trying combine Bitfields with Rails 4.2 and have a problem. 
In 4.2 changed_attributes works different way and there is a problem in line 183:
```ruby
if defined? changed_attributes
  send(:changed_attributes).merge!(bit_name.to_s => old_value)
end
```

I tried fix it by using attributes_changed_by_setter alias (check lukasztackowiak/bitfields@1bda52396121cb48f31d4bc36cfaaac2ecc441e5) but this caused more issues deeper in Rails. I can try dig deeper and maybe fix that but I'm not sure if that piece of code is really needed. I don't see any place where Bitfields relay on changed_attributes and for Rails I think it doesn't matter - it still keep information about changes in bitfield column.
Can you take a look and let me know if I should hunt for more complex solution or simply can remove this part from Bitfields code?

**Comment by grosser** [comment]
0.5.0 kicked out all the changes stuff since that now is used all over the place in AR -> causes lots of issues
-> use bitfield_changes

TODO bitfield_changes is not very efficient, maybe I'll do another pass, but should be good enough for now ...

**Comment by grosser** [comment]
also added _was / _change / _changed? methods in 0.5.1

**Comment by lukasztackowiak** [comment]
Wow, great job, thanks a lot!
