### ISSUE TITLE
bitfield column (e.g., flags) missing during tests

### ISSUE THREAD

**Issue by canoeberry** [grosser/bitfields#18]
I will keep looking of course, but for some reason, while running integration tests, the bitfield is not available:

`*** NoMethodError Exception: undefined method `flags' for #<WorkItem:0x007ff697151a40>`

It works fine in the normal course of events (e.g., rails server, rails console).

**Comment by canoeberry** [comment]
Well - the issue is that I am running my migrations incorrectly for the test environment. Should have known. Is it possible to delete this issue and pretend I never filed it?

**Comment by grosser** [comment]
No, the @world will remember :)
