### ISSUE TITLE
Deprecation Warnings in AR 5.1/Likely breaking in AR 5.2

### ISSUE THREAD

**Issue by aselder** [grosser/bitfields#29]
ActiveRecord 5.1 deprecated many methods in the Dirty API and they will be going away in ActiveRecord 5.2

The bitfields gem still depends on many of the old methods such as `send("#{column}_was")`.

In addition, the API that bitfields are emulating is the old deprecated API. It's probably a good idea to update this match the new Dirty API.

I'll give this a shot and try to pull together a PR.

**Comment by grosser** [comment]
thx, sounds good!
