### ISSUE TITLE
Why you say that is not possible to configure defaults?

### ISSUE THREAD

**Issue by fabn** [grosser/bitfields#42]
In readme is stated

>[Defaults] afaik it is not possible to have some bits true by default (without monkeypatching AR/see tests) -> choose a good naming like xxx_on / xxx_off to use the default 'false'

But I just had this

```ruby
bitfield :reminders_bits,
         2 ** 0  => :notify_one,
         2 ** 1  => :notify_two,
         2 ** 2  => :notify_three
```

And I want `:notify_two` and `:notify_three` to be true by default, so I just run this migration and everything is working as expected

```ruby
DEFAULT_REMINDER_BITS = [1, 2].inject(0) { |v, k| v | 2 ** k }
change_column_default :model, :reminders_bits, DEFAULT_REMINDER_BITS
```

Is there any drawback in doing this? 

Is it possible that something may break in gem functionalities because of this?

**Comment by grosser** [comment]
yeah, readme is wrong / misleading ... not sure why I added that

**Comment by grosser** [comment]
I pushed an update ... this was meant for things like `Product.new.foobar == true`
